---
kind: pipeline
type: kubernetes
name: default

steps: 
  - name: compile
    image: python:3
    commands:
    - pip install -U sphinx
    - make html

  - name: build
    image: plugins/docker
    settings:
      username: robot$tech-doc
      password:
        from_secret: REGISTRY_PASSWORD
      repo: registry.apps.deustotech.eu/reach/reach-tech-doc
      registry: registry.apps.deustotech.eu
      tags: ${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}

  - name: deploy
    image: danielgormly/drone-plugin-kube:0.0.1
    settings:
      template: kubernetes/deployment.yaml
      server: https://rancher.deustotech.eu/k8s/clusters/c-tfxjq
      token:
        from_secret: SAC_TOKEN
      ca:
        from_secret: PLUGIN_CA
    