---
kind: pipeline
type: kubernetes
name: default

steps: 
  - name: compile
    image: python:3
    commands:
    - pip install -U sphinx sphinx-rtd-theme sphinxemoji sphinxext-remoteliteralinclude
    - make html

  - name: build
    image: plugins/docker
    settings:
      username: robot$tech-doc
      password:
        from_secret: REGISTRY_PASSWORD
      repo: registry.apps.deustotech.eu/reach/reach-tech-doc
      registry: registry.apps.deustotech.eu
      tags: ${DRONE_SOURCE_BRANCH//\//-}-${DRONE_BUILD_NUMBER}

  - name: variable-replacement
    image: alpine
    commands:
    - export ENV_NAMESPACE_NAME=$(echo $DRONE_SOURCE_BRANCH | sed 's/[\/.]/-/g')
    - apk add gettext
    - cat kubernetes/service.yaml | envsubst > kubernetes/service-dist.yaml
    - cat kubernetes/ingress.yaml | envsubst > kubernetes/ingress-dist.yaml
    - cat kubernetes/namespace.yaml | envsubst > kubernetes/namespace-dist.yaml
    - cat kubernetes/deployment.yaml | envsubst > kubernetes/deployment-dist.yaml
    environment:
      ENV_DRONE_SOURCE_BRANCH: ${DRONE_SOURCE_BRANCH//\//-}
      ENV_DRONE_BUILD_NUMBER: ${DRONE_BUILD_NUMBER}

  - name: create-namespace
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server: https://rancher.deustotech.eu/k8s/clusters/c-tfxjq
      kubernetes_token:
        from_secret: SAC_TOKEN
    commands:
      - export ENV_NAMESPACE_NAME=$(echo $DRONE_SOURCE_BRANCH | sed 's/[\/.]/-/g')
      - echo $ENV_NAMESPACE_NAME
      - kubectl apply -f kubernetes/namespace-dist.yaml
      - kubectl annotate namespace --overwrite=true reach-tech-doc-$ENV_NAMESPACE_NAME field.cattle.io/projectId=c-tfxjq:p-2wgnk

  - name: deploy
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server: https://rancher.deustotech.eu/k8s/clusters/c-tfxjq
      kubernetes_token:
        from_secret: SAC_TOKEN
    commands:
      - kubectl apply -f kubernetes/deployment-dist.yaml

  - name: service
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server: https://rancher.deustotech.eu/k8s/clusters/c-tfxjq
      kubernetes_token:
        from_secret: SAC_TOKEN
    commands:
      - export ENV_NAMESPACE_NAME=$(echo $DRONE_SOURCE_BRANCH | sed 's/[\/.]/-/g')
      - kubectl apply -f kubernetes/service-dist.yaml
      - kubectl apply -f kubernetes/ingress-dist.yaml
      - echo "Congratulations! You can access your deployment at http://${ENV_NAMESPACE_NAME}.docs.reach.apps.deustotech.eu"    