---
kind: pipeline
type: kubernetes
name: default

steps: 
  - name: compile
    image: python:3
    commands:
    - pip install -U sphinx
    - make html

  - name: build
    image: plugins/docker
    settings:
      username: robot$tech-doc
      password:
        from_secret: REGISTRY_PASSWORD
    repo: reach/reach-tech-doc
    registry: registry.apps.deustotech.eu
    tags: ${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}