apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: docs.reach.apps.deustotech.eu
  namespace: reach-tech-doc-${ENV_NAMESPACE_NAME}
spec:
  rules:
  - host: ${ENV_NAMESPACE_NAME}.docs.reach.apps.deustotech.eu
    http:
      paths:
      - backend:
          serviceName: tech-doc
          servicePort: 80