apiVersion: v1
kind: Service
metadata:
  name: tech-doc
  namespace: reach-tech-doc-${ENV_DRONE_SOURCE_BRANCH}
spec:
  selector:
    app: tech-doc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80