name: Delete k8s deployment

# Controls when the action will run. 
on:
  pull_request:
    types: [closed]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
     runs-on: ubuntu-latest
     steps:
      - name: Extract branch name
        shell: bash
        run: |
          export DRONE_SOURCE_BRANCH=${GITHUB_HEAD_REF#refs/heads/}
          echo "##[set-output name=branch;]$(echo $DRONE_SOURCE_BRANCH | sed 's/[\/._]/-/g')"
        id: extract_branch

      - uses: danielr1996/kubectl-action@1.0.0
        name: Delete unused namespace
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          args: delete namespace/reach-tech-doc-${{ steps.extract_branch.outputs.branch }}